<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lipika-Inspiron-3442" name="Test" tests="4" failures="1" timestamp="2 May 2016 09:19:57 GMT" time="61.843" errors="0">
  <testcase name="verifyValidLogin" time="8.29" classname="com.wordpress.testcases.verifyWordpressLogin"/>
  <testcase name="verifyInValidUserIdLogin" time="2.032" classname="com.wordpress.testcases.verifyWordpressLogin">
    <failure type="java.lang.AssertionError" message="Failing the testcase deliberatly">
      <![CDATA[java.lang.AssertionError: Failing the testcase deliberatly
	at com.wordpress.testcases.verifyWordpressLogin.verifyInValidUserIdLogin(verifyWordpressLogin.java:100)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verifyInValidUserIdLogin -->
  <testcase name="verifyInValidPasswordLogin" time="1.718" classname="com.wordpress.testcases.verifyWordpressLogin">
    <skipped/>
  </testcase> <!-- verifyInValidPasswordLogin -->
  <testcase name="verifyLogout" time="13.545" classname="com.wordpress.testcases.verifyWordpressLogin"/>
</testsuite> <!-- Test -->
